apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-yxsv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-yxsv
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-yxsv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-yxsv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-yxsv
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-lzrl-tenant/dotnet-component/devfile-sample-dotnet60-basic-yxsv@sha256:e56ade8e6f35a4cd7f9cf7ee3870adc36d16293de4bc4e45c363c1956408b3b5
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
